trigger:
- master

pool:
  vmImageName: 'ubuntu-18.04'

steps:
- task: Docker@0
  displayName: 'Build an image'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerFile: Dockerfile
    imageName: '9870050478/springboot-petclinic-docker:$(Build.BuildId)'

- task: Docker@0
  displayName: 'Push an image'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: dockerhub
    action: 'Push an image'
    imageName: '9870050478/springboot-petclinic-docker:$(Build.BuildId)'

- task: SSH@0
  displayName: 'Run shell commands on remote machine'
  inputs:
    sshEndpoint: 'ec2-instance'
    commands: |
     docker login
     docker run -it -d  -p 8081:8080 9870050478/springboot-petclinic-docker:$(Build.BuildId)
    interactiveSession: true
