trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

steps:
  - script: echo Hello, World !
    displayName: 'Run a one line script'

  - script: |
      echo Hello, World!
    displayName: 'Run a one line script'
