apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-petclinic
  template:
    metadata:
      labels:
        app: springboot-petclinic
    spec:
      containers:
      - name: springboot-petclinic
        image: 9870050478/springboot-petclinic:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-petclinic-svc
spec:
  selector:
    app: springboot-petclinic
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8080
  type: LoadBalancer
